[mypy]
python_version = 3.9
ignore_missing_imports = True
disallow_untyped_defs = False
warn_unused_ignores = True
warn_return_any = False
show_error_codes = True
pretty = True
follow_imports = skip

[mypy-jax.*]
ignore_missing_imports = True

[mypy-jaxlib.*]
ignore_missing_imports = True
